apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: pronto
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
        memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis